version: 1.2
workflows:
  - name: bulkRNA_workflow
    subclass: WDL
    publish: True
    primaryDescriptorPath: /bulkAtlas/RNA_pipeline.wdl
    testParameterFiles: 
      - /bulkAtlas/conf/inputs_hg38_STAR_fusion.json
    authors:
      - name: jkalfon
        email: jkalfon@whitelabgx.com
  - name: bulkRNA_germline_variant_workflow
    subclass: WDL
    publish: True
    primaryDescriptorPath: /bulkAtlas/rnaseq-germline-snps-indels.wdl
    testParameterFiles:
      - /bulkAtlas/conf/inputs_rnaseq-germline-snps-indels.json
    authors:
      - name: jkalfon
        email: jkalfon@whitelabgx.com
  - name: optimus_workflow
    subclass: WDL
    publish: True
    primaryDescriptorPath: /scAtlas/optimus/Optimus.wdl
    testParameterFiles:
      - /scAtlas/optimus/test_data/8k_pbmc_v2_inputs.json
    authors:
      - name: xliu
        email: xliu@whitelabgx.com  
  - name: smartseq_single_sample_workflow
    subclass: WDL
    publish: True
    primaryDescriptorPath: /scAtlas/smartseq2_single_sample/SmartSeq2SingleSample.wdl
    testParameterFiles:
      - /scAtlas/smartseq2_single_sample/test_data/human_single_example_inputs.json 
    authors:
      - name: dzielinski
        email: dzielinski@whitelabgx.com
  - name: smartseq_multi_sample_workflow
    subclass: WDL
    publish: True
    primaryDescriptorPath: /scAtlas/smartseq2_multisample/MultiSampleSmartSeq2.wdl
    testParameterFiles:
      - /scAtlas/smartseq2_multisample/test_data/human_single_example_inputs.json
    authors:
      - name: dzielinski
        email: dzielinski@whitelabgx.com