version: 1.2
workflows:
  - name: RNA_pipeline
    subclass: WDL
    publish: True
    primaryDescriptorPath: /bulkAtlas/RNA_pipeline.wdl
    testParameterFiles:
      - /test.json
    authors:
      - name: jkalfon
        email: jkalfon@whitelabgx.com

  - name: RNA_preprocessing_pipeline
    subclass: WDL
    publish: True
    primaryDescriptorPath: /bulkAtlas/RNA_preprocessing_pipeline.wdl
    testParameterFiles:
      - /test.json
    authors:
      - name: jkalfon
        email: jkalfon@whitelabgx.com

  - name: rnaseq-germline-snps-indels
    subclass: WDL
    publish: True
    primaryDescriptorPath: /bulkAtlas/rnaseq-germline-snps-indels.wdl
    testParameterFiles:
      - /test.json
    authors:
      - name: jkalfon
        email: jkalfon@whitelabgx.com
