#!/bin/bash

cd /cromwell-executions/Optimus/a0c421eb-3fda-417f-a8c1-7918278c7e97/call-ReferenceCheck/execution
tmpDir=$(mkdir -p "/cromwell-executions/Optimus/a0c421eb-3fda-417f-a8c1-7918278c7e97/call-ReferenceCheck/tmp.2760cf59" && echo "/cromwell-executions/Optimus/a0c421eb-3fda-417f-a8c1-7918278c7e97/call-ReferenceCheck/tmp.2760cf59")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/Optimus/a0c421eb-3fda-417f-a8c1-7918278c7e97/call-ReferenceCheck/execution

)
outa0c421eb="${tmpDir}/out.$$" erra0c421eb="${tmpDir}/err.$$"
mkfifo "$outa0c421eb" "$erra0c421eb"
trap 'rm "$outa0c421eb" "$erra0c421eb"' EXIT
touch '/cromwell-executions/Optimus/a0c421eb-3fda-417f-a8c1-7918278c7e97/call-ReferenceCheck/execution/stdout' '/cromwell-executions/Optimus/a0c421eb-3fda-417f-a8c1-7918278c7e97/call-ReferenceCheck/execution/stderr'
tee '/cromwell-executions/Optimus/a0c421eb-3fda-417f-a8c1-7918278c7e97/call-ReferenceCheck/execution/stdout' < "$outa0c421eb" &
tee '/cromwell-executions/Optimus/a0c421eb-3fda-417f-a8c1-7918278c7e97/call-ReferenceCheck/execution/stderr' < "$erra0c421eb" >&2 &
(
cd /cromwell-executions/Optimus/a0c421eb-3fda-417f-a8c1-7918278c7e97/call-ReferenceCheck/execution


# check genomic reference version and print to output txt file
STRING=gs://gcp-public-data--broad-references/hg38/v0/star/star_2.7.9a_primary_gencode_human_v27.tar
BASE=$(basename $STRING .tar)
IFS=' -' read -r -a array <<< $BASE
REFERENCE=${array[2]}
VERSION=${array[4]}
ANNOTATION=${array[5]}

echo -e "$REFERENCE\n$VERSION\n$ANNOTATION" > reference_version.txt
echo Reference is $REFERENCE
echo Version is $VERSION
echo Annotation is $ANNOTATION
)  > "$outa0c421eb" 2> "$erra0c421eb"
echo $? > /cromwell-executions/Optimus/a0c421eb-3fda-417f-a8c1-7918278c7e97/call-ReferenceCheck/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/Optimus/a0c421eb-3fda-417f-a8c1-7918278c7e97/call-ReferenceCheck/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/Optimus/a0c421eb-3fda-417f-a8c1-7918278c7e97/call-ReferenceCheck/execution
sync


)
mv /cromwell-executions/Optimus/a0c421eb-3fda-417f-a8c1-7918278c7e97/call-ReferenceCheck/execution/rc.tmp /cromwell-executions/Optimus/a0c421eb-3fda-417f-a8c1-7918278c7e97/call-ReferenceCheck/execution/rc
